version: "3"

services:
  template-finder:
    build: .
    command: yarn start
    volumes:
      - ./src:/app/src
      - ./node_modules:/app/node_modules
    ports:
      - "3333:3333"
    networks:
      - backend
    environment:
      NODE_ENV: development
    env_file:
      - .env

networks:
  backend:
    driver: "bridge"
